version: "3.8"
services:
  vconvert:
    image: .
    container_name: vconvert
    volumes:
      # input dir
      - /usr/local/transmission/download:/vconvert_input
      # log dir
      - /var/log/vconvert:/vconvert/logs
    #restart: on-failure