version: "3.8"
services:
  vconvert:
    build: .
    #image: lizkes/vconvert:latest
    volumes:
      # input dir
      - /download:/vconvert
      # log dir
      - /var/log/vconvert:/var/log/vconvert
    #restart: on-failure