version: "3.8"
services:
  vconvert:
    build: .
    container_name: vconvert
    volumes:
      - /usr/local/transmission/download:/vconvert_input
      - /var/log/vconvert/:/usr/local/vconvert/app/logs/
    #restart: on-failure